# Generated by Django 4.2.20 on 2025-03-14 16:12

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('posterimage', models.ImageField(blank=True, upload_to='poster/%Y/%m/%d')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('duration', models.TextField(blank=True, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Rating', models.TextField(blank=True, choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('A', 'A')], max_length=6)),
                ('genre', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seats_row', models.PositiveIntegerField(blank=True)),
                ('num_seats', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('price', models.PositiveIntegerField(verbose_name='Ticket Price')),
                ('showtime', models.TimeField(blank=True, null=True, verbose_name='Showtime')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='show_times', to='movies.movie')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='running_shows', to='movies.room')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_num', models.CharField(max_length=25)),
                ('booked', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_num', to='movies.show')),
            ],
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['-showtime'], name='movies_show_showtim_260e45_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-created'], name='movies_movi_created_4f7274_idx'),
        ),
    ]
