# Generated by Django 4.2.20 on 2025-03-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
