# Generated by Django 4.2.20 on 2025-03-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('bookings', '0002_delete_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingseats',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='movies.seat'),
        ),
        migrations.AddField(
            model_name='bookingseats',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='movies.show'),
        ),
    ]
