# Generated by Django 4.2.20 on 2025-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingseats_seat_bookingseats_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseats',
            name='seat',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
