# Generated by Django 4.2.20 on 2025-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_bookingseats_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingseats',
            name='booking_code',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
