# Generated by Django 4.2.20 on 2025-03-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_bookingseats_booking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(default='5952090d', max_length=100),
        ),
    ]
